### ISSUE TITLE
sometimes crashes with "stack smashing detected"

### ISSUE THREAD

**Issue by NicoWeio** [ddccontrol/ddccontrol#99]
Sometimes and seemingly randomly, I get the following error:

```
$ sudo ddccontrol -r 0x10 dev:/dev/i2c-3
ddccontrol version 0.5.1
Copyright 2004-2005 Oleg I. Vdovikin (oleg@cs.msu.su)
Copyright 2004-2006 Nicolas Boichat (nicolas@boichat.ch)
This program comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of this program under the terms of the GNU General Public License.

Reading EDID and initializing DDC/CI at bus dev:/dev/i2c-3...
*** stack smashing detected ***: terminated
```

I wrote my own `DELF042.xml` which reads
```xml
<?xml version="1.0"?>
<monitor name="Dell P2213" init="standard">
	<control id="brightness" address="0x10"/> 
</monitor>
```
but I don't think this is the culprit, as it does work _sometimes_.

**Comment by genodeftest** [comment]
Can you try to install debug infos and execute ddccontrol in `gdb`? This should give you a hint what goes wrong.

The fact that it works _sometimes_ looks like some illegal memory access, e.g. reading/writing beyond the limits of an array.

**Comment by NicoWeio** [comment]
I'm not at all familiar with `gdb`, but I'll give it a try.

**Comment by 1player** [comment]
I can reproduce it by simply capturing the output to a variable.

```
$ output=$(ddccontrol -r 0x10 -w 50 dev:/dev/i2c-5 2>&1 | tail -n 1); echo $output

$ output=$(ddccontrol -r 0x10 -w 50 dev:/dev/i2c-5 2>&1 | tail -n 1); echo $output
Control 0x10: +/50/100 C [Brightness]
$ output=$(ddccontrol -r 0x10 -w 50 dev:/dev/i2c-5 2>&1 | tail -n 1); echo $output
*** stack smashing detected ***: terminated
$ output=$(ddccontrol -r 0x10 -w 50 dev:/dev/i2c-5 2>&1 | tail -n 1); echo $output

$ output=$(ddccontrol -r 0x10 -w 50 dev:/dev/i2c-5 2>&1 | tail -n 1); echo $output
*** stack smashing detected ***: terminated
$ output=$(ddccontrol -r 0x10 -w 50 dev:/dev/i2c-5 2>&1 | tail -n 1); echo $output
```

As you can see, out of 6 runs, crashes 2 times with a `stack smashing detected` error, 3 times does nothing at all, and worked once. If I don't capture the output, works every time.

Btw, this is logged to syslog when it crashes:

```
[42250.484422] ddccontrol[169243]: segfault at 7ffd0632e000 ip 00007f6c737fe035 sp 00007ffd0632be40 error 6 in libddccontrol.so.0.0.0[7f6c737fc000+8000]
[42250.484427] Code: 80 fa 29 0f 84 46 03 00 00 80 fa 20 0f 84 3d 03 00 00 b8 01 00 00 00 4c 8d 44 24 3f eb 0c 0f 1f 80 00 00 00 00 80 fa 29 74 14 <41> 88 14 00 0f b6 14 06 48 63 f8 48 83 c0 01 80 fa 20 75 e7 48 8b
```

**Comment by 1player** [comment]
Well, I can't reproduce it anymore. What I previously did was run a `ddccontrol -p -c -d` and I Ctrl-C'd halfway. Now I've run it to completion and everything seems to work. Did I perhaps leave my monitor in a weird state that was causing ddccontrol to crash?

**Comment by Druneau** [comment]
I recently started using ddccontrol.  I've noticed some stack smashing aswell.  Unsure if it's the same situation, but simply reading brightness will trigger it fairly often.

Thread 4 (Thread 0x7fffe97fe6c0 (LWP 81405) "gdbus"):
#0  0x00007ffff7eb4bed in poll () at /lib64/libc.so.6
#1  0x00007ffff79cfeb4 in g_main_context_iterate_unlocked.isra () at /lib64/libglib-2.0.so.0
#2  0x00007ffff7976447 in g_main_loop_run () at /lib64/libglib-2.0.so.0
#3  0x00007ffff7b7f592 in gdbus_shared_thread_func.lto_priv () at /lib64/libgio-2.0.so.0
#4  0x00007ffff79a5523 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#5  0x00007ffff7e3b897 in start_thread () at /lib64/libc.so.6
#6  0x00007ffff7ec280c in clone3 () at /lib64/libc.so.6

Thread 3 (Thread 0x7fffe3fff6c0 (LWP 81404) "gmain"):
#0  0x00007ffff7eb4bed in poll () at /lib64/libc.so.6
#1  0x00007ffff79cfeb4 in g_main_context_iterate_unlocked.isra () at /lib64/libglib-2.0.so.0
#2  0x00007ffff7972ad3 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#3  0x00007ffff7972b29 in glib_worker_main () at /lib64/libglib-2.0.so.0
#4  0x00007ffff79a5523 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#5  0x00007ffff7e3b897 in start_thread () at /lib64/libc.so.6
#6  0x00007ffff7ec280c in clone3 () at /lib64/libc.so.6

Thread 2 (Thread 0x7fffe9fff6c0 (LWP 81403) "pool-spawner"):
#0  0x00007ffff7ec060d in syscall () at /lib64/libc.so.6
#1  0x00007ffff79ccb2d in g_cond_wait () at /lib64/libglib-2.0.so.0
#2  0x00007ffff794022b in g_async_queue_pop_intern_unlocked () at /lib64/libglib-2.0.so.0
#3  0x00007ffff79a9393 in g_thread_pool_spawn_thread () at /lib64/libglib-2.0.so.0
#4  0x00007ffff79a5523 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#5  0x00007ffff7e3b897 in start_thread () at /lib64/libc.so.6
#6  0x00007ffff7ec280c in clone3 () at /lib64/libc.so.6

Thread 1 (Thread 0x7ffff7616800 (LWP 81402) "ddccontrol"):
#0  0x00007ffff7e3d834 in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007ffff7deb8ee in raise () at /lib64/libc.so.6
#2  0x00007ffff7dd38ff in abort () at /lib64/libc.so.6
#3  0x00007ffff7dd47d0 in __libc_message.cold () at /lib64/libc.so.6
#4  0x00007ffff7ed0e29 in __fortify_fail () at /lib64/libc.so.6
#5  0x00007ffff7ed20b4 in __stack_chk_fail () at /lib64/libc.so.6
#6  0x00007ffff7fa079e in ddcci_parse_caps (caps_str=<optimized out>, caps=caps@entry=0x555555637c90, add=add@entry=1) at /usr/src/debug/ddccontrol-0.6.1-2.fc39.x86_64/src/lib/ddcci.c:771
        pos = <optimized out>
        level = <optimized out>
        svcp = <optimized out>
        stype = <optimized out>
        buf = "1\000\001\000\000\000\000\000\000!\000\000\000\000\000\000\000\360\261VUUU", '\000' <repeats 18 times>, "Q", '\000' <repeats 31 times>, "\3408cUUU", '\000' <repeats 18 times>, "0OcUUU\000\000\000ZcUUU\000\000\000\000\000\000\000\000\000\000!\000\000\000\000\000"
        endptr = 0x7fffffffe1d1 ""
        ind = <optimized out>
        val = <optimized out>
        i = <optimized out>
        removeprevious = <optimized out>
        num = <optimized out>
#7  0x00007ffff7f95946 in ddcci_dbus_open (proxy=proxy@entry=0x55555556b1f0, _mon=_mon@entry=0x7fffffffe350, filename=filename@entry=0x7fffffffe745 "dev:/dev/i2c-14") at /usr/src/debug/ddccontrol-0.6.1-2.fc39.x86_64/src/daemon/dbus_client.c:86
        pnpid = 0x7fffd4003f30 "GSM5B7F"
        error = 0x0
        dbus_mon = 0x555555637c50
        mon = 0x555555637c50
        result = <optimized out>
#8  0x000055555555697a in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/ddccontrol-0.6.1-2.fc39.x86_64/src/ddccontrol/main.c:340
        i = <optimized out>
        retry = <optimized out>
        ret = <optimized out>
        proxy = <optimized out>
        mon = 0x555555637c50
        fn = 0x7fffffffe745 "dev:/dev/i2c-14"
        datadir = <optimized out>
        pnpname = <optimized out>
        profilefile = <optimized out>
        dump = 0
        ctrl = <optimized out>
        value = <optimized out>
        relative = <optimized out>
        caps = 0
        save = 0
        force = 0
        verbosity = <optimized out>
        probe = 0
Not confirmed.

**Comment by genodeftest** [comment]
Could you please post the stack with debug symbols installed, especially debug symbols for your libc and glib?

**Comment by Druneau** [comment]
I sat down to reproduce and it's not doing it any more...  Nothing changed except 2 reboots.  I will keep an eye out and repost new stacktrace if it starts doing it again!
